version: "3.5"

services:
  db:
    container_name: dejavu-mysql
    image: mysql/mysql-server:5.7.23
    networks:
      - sonarnet
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sonar
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
    volumes:
      - type: volume
        source: mysql-server-5.7
        target: /var/lib/mysql
    volumes:
      - type: volume
        source: mysql-server-5.7-conf
        target: /etc/mysql
    restart: always

  sonarqube:
    depends_on:
      - db
    container_name: dejavu-sonarqube
    image: sonarqube
    networks:
      - sonarnet
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - type: volume
        source: sonarqube_conf
        target: /opt/sonarqube/conf
      - type: volume
        source: sonarqube_data
        target: /opt/sonarqube/data
      - type: volume
        source: sonarqube_extensions
        target: /opt/sonarqube/extensions
      - type: volume
        source: sonarqube_bundled-plugins
        target: /opt/sonarqube/lib/bundled-plugins
    restart: always

  jenkins:
    depends_on:
      - sonarqube
    container_name: dejavu-jenkins
    image: jenkins/jenkins:lts
    networks:
      - sonarnet
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - sonarnet
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    restart: always

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  mysql-server-5.7:
  mysql-server-5.7-conf:
  jenkins_home:
